const btn = document.querySelector("#btn");
const btnAfter = document.querySelector(".btn_after");

const characters = [
    {
        Name: "細川とわ",
        HP: 30,
        MAXHP: 30,
        ATK: 140,
        DEF: 70,
        SPD: 70,
        IMG: "img/hosokawa.jpg",
        TURN: false,
    },
    {
        Name: "えもじの子",
        HP: 100,
        MAXHP: 100,
        ATK: 50,
        DEF: 50,
        SPD: 85,
        IMG: "img/emojinoko.jpg",
        TURN: false,
    },
    {
        Name: "フクシマ",
        HP: 50,
        MAXHP: 50,
        ATK: 40,
        DEF: 80,
        SPD: 60,
        IMG: "img/fukusima.jpg",
        TURN: false,
    },
    {
        Name: "ハラバリー",
        HP: 109,
        MAXHP: 109,
        ATK: 64,
        DEF: 91,
        SPD: 45,
        IMG: "img/harabari.jpg",
        TURN: false,
    },
    {
        Name: "地雷系少女",
        HP: 60,
        MAXHP: 60,
        ATK: 100,
        DEF: 30,
        SPD: 90,
        IMG: "img/jiraikei.JPG",
        TURN: false,
    },
    {
        Name: "黄ばみフクシマ",
        HP: 20,
        MAXHP: 20,
        ATK: 120,
        DEF: 60,
        SPD: 10,
        IMG: "img/kigami_shunya.jpg",
        TURN: false,
    },
    {
        Name: "モフレム",
        HP: 19,
        MAXHP: 19,
        ATK: 91,
        DEF: 90,
        SPD: 42,
        IMG: "img/mohuremu.jpg",
        TURN: false,
    },
    {
        Name: "モナリザ",
        HP: 70,
        MAXHP: 70,
        ATK: 99,
        DEF: 22,
        SPD: 55,
        IMG: "img/monariza.jpg",
        TURN: false,
    },
    {
        Name: "ナッシー",
        HP: 95,
        MAXHP: 95,
        ATK: 95,
        DEF: 85,
        SPD: 55,
        IMG: "img/nassy.jpg",
        TURN: false,
    },
    {
        Name: "ネイズ",
        HP: 8,
        MAXHP: 8,
        ATK: 14,
        DEF: 75,
        SPD: 5,
        IMG: "img/neizu.jpg",
        TURN: false,
    },
    {
        Name: "ニンゲン",
        HP: 32,
        MAXHP: 32,
        ATK: 83,
        DEF: 49,
        SPD: 72,
        IMG: "img/ningen.jpg",
        TURN: false,
    },
    {
        Name: "ウリムー",
        HP: 50,
        MAXHP: 50,
        ATK: 50,
        DEF: 40,
        SPD: 50,
        IMG: "img/urimu.JPG",
        TURN: false,
    },
    {
        Name: "アヒル",
        HP: 65,
        MAXHP: 65,
        ATK: 58,
        DEF: 52,
        SPD: 78,
        IMG: "img/ahiru.JPG",
        TURN: false,
    },
    {
        Name: "さかぐち猗窩座",
        HP: 68,
        MAXHP: 68,
        ATK: 110,
        DEF: 78,
        SPD: 38,
        IMG: "img/akaza.jpg",
        TURN: false,
    },
    {
        Name: "綾鷹",
        HP: 82,
        MAXHP: 82,
        ATK: 76,
        DEF: 88,
        SPD: 54,
        IMG: "img/ayataka.png",
        TURN: false,
    },
    {
        Name: "ムーキーベッツ",
        HP: 74,
        MAXHP: 74,
        ATK: 92,
        DEF: 68,
        SPD: 93,
        IMG: "img/bettu.JPG",
        TURN: false,
    },
    {
        Name: "細川とわ（美人）",
        HP: 64,
        MAXHP: 64,
        ATK: 122,
        DEF: 66,
        SPD: 88,
        IMG: "img/bijin_hosokawa.jpg",
        TURN: false,
    },
    {
        Name: "坂口こうへい（泥酔）",
        HP: 90,
        MAXHP: 90,
        ATK: 105,
        DEF: 40,
        SPD: 25,
        IMG: "img/deisui_sakaguti.jpg",
        TURN: false,
    },
    {
        Name: "ドラえもん",
        HP: 95,
        MAXHP: 95,
        ATK: 88,
        DEF: 92,
        SPD: 60,
        IMG: "img/doraemon.jpg",
        TURN: false,
    },
    {
        Name: "フィンくん",
        HP: 58,
        MAXHP: 58,
        ATK: 86,
        DEF: 44,
        SPD: 97,
        IMG: "img/finkun.JPG",
        TURN: false,
    },
    {
        Name: "はくさい泥棒",
        HP: 77,
        MAXHP: 77,
        ATK: 84,
        DEF: 59,
        SPD: 91,
        IMG: "img/hakusaidorobou.jpg",
        TURN: false,
    },
    {
        Name: "ひよこ",
        HP: 52,
        MAXHP: 52,
        ATK: 73,
        DEF: 48,
        SPD: 89,
        IMG: "img/hiyoko.png",
        TURN: false,
    },
    {
        Name: "細川とわ（化け物）",
        HP: 48,
        MAXHP: 48,
        ATK: 96,
        DEF: 52,
        SPD: 74,
        IMG: "img/hosokawa_bakemono.jpg",
        TURN: false,
    },
    {
        Name: "細川とわ（獣神化）",
        HP: 92,
        MAXHP: 92,
        ATK: 138,
        DEF: 94,
        SPD: 10,
        IMG: "img/hosokawa_jusinka.jpg",
        TURN: false,
    },
    {
        Name: "自認レゼ",
        HP: 38,
        MAXHP: 38,
        ATK: 44,
        DEF: 28,
        SPD: 52,
        IMG: "img/jininreze.jpg",
        TURN: false,
    },
    {
        Name: "つぶらなカボス",
        HP: 72,
        MAXHP: 72,
        ATK: 36,
        DEF: 64,
        SPD: 58,
        IMG: "img/kabosu.png",
        TURN: false,
    },
    {
        Name: "キコノ",
        HP: 46,
        MAXHP: 46,
        ATK: 62,
        DEF: 34,
        SPD: 71,
        IMG: "img/kikono.PNG",
        TURN: false,
    },
    {
        Name: "細川とわ（真顔）",
        HP: 88,
        MAXHP: 88,
        ATK: 118,
        DEF: 110,
        SPD: 72,
        IMG: "img/magao_hosokawa.png",
        TURN: false,
    },
    {
        Name: "魔神さかぐち",
        HP: 109,
        MAXHP: 108,
        ATK: 142,
        DEF: 38,
        SPD: 46,
        IMG: "img/majin_sakaguti.JPG",
        TURN: false,
    },
    {
        Name: "なんJ民",
        HP: 22,
        MAXHP: 22,
        ATK: 18,
        DEF: 12,
        SPD: 33,
        IMG: "img/nanjmin.png",
        TURN: false,
    },
    {
        Name: "パン",
        HP: 34,
        MAXHP: 34,
        ATK: 26,
        DEF: 18,
        SPD: 61,
        IMG: "img/pan.JPG",
        TURN: false,
    },
    {
        Name: "坂倉先生",
        HP: 86,
        MAXHP: 86,
        ATK: 112,
        DEF: 98,
        SPD: 78,
        IMG: "img/sakakura.jpg",
        TURN: false,
    },
    {
        Name: "パペットスンスン",
        HP: 58,
        MAXHP: 58,
        ATK: 74,
        DEF: 63,
        SPD: 92,
        IMG: "img/sunsun.jpg",
        TURN: false,
    },
    {
        Name: "Nissy",
        HP: 24,
        MAXHP: 24,
        ATK: 224,
        DEF: 102,
        SPD: 104,
        IMG: "img/super_nissy.jpg",
        TURN: false,
    },
    {
        Name: "滝本先生",
        HP: 150,
        MAXHP: 150,
        ATK: 165,
        DEF: 160,
        SPD: 140,
        IMG: "img/takimoto.jpg",
        TURN: false,
    },
    {
        Name: "山本由伸",
        HP: 104,
        MAXHP: 104,
        ATK: 148,
        DEF: 132,
        SPD: 96,
        IMG: "img/yamamoto.jpg",
        TURN: false,
    },
    {
        Name: "ぜつぼうくん",
        HP: 30,
        MAXHP: 30,
        ATK: 24,
        DEF: 20,
        SPD: 27,
        IMG: "img/zetubou.png",
        TURN: false,
    },
];

btn.addEventListener("click", () => {
    setTimeout(() => {
        btnAfter.style.display = "flex";
    }, 300);
    const randomNum = Math.floor(Math.random() * characters.length);
    const cpuRandomNum = Math.floor(Math.random() * characters.length);
    localStorage.setItem("myCharacter", JSON.stringify(characters[randomNum]));
    localStorage.setItem("cpuCharacter", JSON.stringify(characters[cpuRandomNum]));
    btnAfter.innerHTML = `
          <h2>ガチャ結果</h2>
        <img src="${characters[randomNum].IMG}" alt=""/>
        <h2>${characters[randomNum].Name}がとびだしてきた!!!!</h2>
        <a href="battle.html">バトルしにいく！！！</a>
  `;
});
